# Generated by Django 6.0.1 on 2026-01-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0004_alter_flight_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="destination",
            field=models.CharField(max_length=64),
        ),
    ]
